name: 'Housekeeping - Container Registry'

on:
  push:
    branches:
    - ci/regsitry-housekeeping
    - main
  schedule:
    - cron: '0 6 * * 1'     # Mondays at 6am
  workflow_dispatch:        # Allow manual runs

permissions:
  id-token: write
  contents: read

env:
  acr-registry: cloudkubereviews
  naming-pattern: 'frontend:dev-*'
  keep-days: 14d
  keep-last: 5

jobs:
  housekeeping-dev:
    name: ' 🧹 dev images'
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'az login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: 'az acr login'
      run: az acr login --name ${{ env.acr-registry }}

    # For details on `acr purge` command, see
    # https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge
    - name: 'acr purge'
      run: |
        RUN_TIDY="acr purge --filter ${{ env.naming-pattern }} --untagged --ago ${{ env.keep-days }} --keep ${{ env.keep-last }}"
        az acr run --cmd "$RUN_TIDY" --registry ${{ env.acr-registry }} /dev/null
